# Generated by Django 5.1.4 on 2025-01-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_completed_task_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtask',
            name='coin_reward',
        ),
        migrations.RemoveField(
            model_name='customtask',
            name='exp_reward',
        ),
    ]
