# Generated by Django 5.1.4 on 2025-01-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_userprofile_coins_alter_userprofile_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
