# Generated by Django 5.1.4 on 2025-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='exp_reward',
            field=models.IntegerField(default=0),
        ),
    ]
