# Generated by Django 5.1.4 on 2025-01-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_customtask_exp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='exp_reward',
            field=models.IntegerField(choices=[(50, '50 EXP'), (75, '75 EXP'), (100, '100 EXP')], default=50),
        ),
    ]
