# Generated by Django 5.1.4 on 2025-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_customtask_exp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='exp_reward',
            field=models.IntegerField(default=0),
        ),
    ]
