# Generated by Django 5.1.4 on 2025-01-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_usercustomtaskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomtaskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.customtask'),
        ),
    ]
