# Generated by Django 5.1.4 on 2025-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_usercustomtaskcompletion_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='exp_reward',
            field=models.IntegerField(choices=[(0, '0 EXP'), (50, '50 EXP'), (75, '75 EXP'), (100, '100 EXP')], default=0),
        ),
    ]
